services:
  - type: web
    name: face-test-backend2
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/face-test-backend2-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
